### PR TITLE
Login UI completed

### PR DESCRIPTION
**Pull request by areeba-farooq**
Hello, the login UI is completed. Kindly check and let me know if you want any changes.

### CODE REVIEW

**Comment by elysian12** [comment]
@SmartAree  there are conflicts in the pr.
Please fix the merge confict and create a pr again

**Comment by elysian12** [comment]
@SmartAree please follow the architecture/pattern

**Comment by areeba-farooq** [comment]
ok

**Comment by areeba-farooq** [comment]
Done. Kindly merge it. Thankyou

**Pull request merged**
